name: Maven Cache CI

steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'
      architecture: x64
      cache: 'maven'

  - name: Build with Maven
    run: mvn -B package --file pom.xml
